### ISSUE TITLE
osu lazer support

### ISSUE THREAD

**Issue by AuracleTech** [Tillerino/Tillerinobot#228]
Tillerino doesn't read /np from lazer 😢

**Comment by Tillerino** [comment]
Oh is that a separate system or something? Does anybody know more?

**Comment by AlexandraCat** [comment]
> Oh is that a separate system or something? Does anybody know more?

Yop!
So basically I was wondering as well..
In osu!lazer you can't receive any info about "/np". From main menu it says: "listening to: .." and in game: "is playing ..."
But neither of these works.
Other commands do things as usual.

I can provide any info you needed.

Looking for your response,
UwU.

**Comment by Tillerino** [comment]
Wait, so we do read messages from lazer somehow? So when a player goes `!r` in lazer, they get a response from the bot?
Just the `/np` command doesn't work because that's not a thing in lazer anymore?

**Comment by AuracleTech** [comment]
Yeah from what I recall that's it

**Comment by AlexandraCat** [comment]
> Wait, so we do read messages from lazer somehow? So when a player goes `!r` in lazer, they get a response from the bot? Just the `/np` command doesn't work because that's not a thing in lazer anymore?

Yeah, exactly.

**Comment by AuracleTech** [comment]
> But I didn't get what you mean by this: _"Just the `/np` command d...

You can still use regular commands sent as "message" like !r or !help
But you cannot use `/np` because it's not sent as a message but as its own separate thing

**Comment by omkelderman** [comment]
`/np` has always been a non normal message. On the stable client irc bridge its an irc ACTION instead of an PRIVMSG. Now the real question here is what is happening with the lazer messaging system when it gets forwarded somewhere in the osu backend to the irc gateway. That'll need a little bit of investigation.

I'll see what I can find out soon

**Comment by AlexandraCat** [comment]
So basically you guys mean that you're working on it or something like that?
Kinda really want this to work, haha. And I hope not only me so..
Waiting for the results. And speaking about them — any clues how much time it can possibly take?

**Comment by omkelderman** [comment]
with the current plan from peppy to open up lazer to pp at the end of the year, i'd say we definitely should be ready for that.
I don't know how much work this will be as I've not looked into it yet, can be anything from an easy 5min fix to impossible lol.
I'll try to find some time to investigate this later today

**Comment by Tillerino** [comment]
Let's see what peppy or says. This probably doesn't take longer than 5 mins to fix on their end, too. Tbh, I can't really imagine why they wouldn't just do that.

**Comment by Tillerino** [comment]
Thanks for your investigation <3

**Comment by Tillerino** [comment]
The upstream issue was closed as fixed. Does this mean that this problem has been solved?

**Comment by omkelderman** [comment]
When that got closed it wasn't deployed yet. There is no indication (that I know of) that a new bancho update has been deployed. For all I know it is now. So basically we just gotta try and see what happens. And if lazer np still doesn't work properly also repeat my wireshark test to confirm it has been deployed in case there's something I missed and it's more than just that bancho issue

**Comment by AlexandraCat** [comment]
As I see It works fine now!

**Comment by Tillerino** [comment]
Excellent! Thanks :)
